/* Sense Bridge V2 — FI. Safe Nordic extension: clone EN defaults, then override translated UI. */
(function(w){"use strict";
const R=(w.SB_I18N=w.SB_I18N||{modules:Object.create(null)}),M=R.modules;
function clone(v){if(Array.isArray(v))return v.map(clone);if(v&&typeof v==="object"){const o={};Object.keys(v).forEach(k=>o[k]=clone(v[k]));return o;}return v;}
Object.keys(M).forEach(id=>{if(M[id]&&M[id].EN!==undefined&&M[id]["FI"]===undefined)M[id]["FI"]=clone(M[id].EN);});
Object.assign(M["m4367_labels"]["FI"],{"light":"☀️ Vaalea","dark":"🌙 Tumma"});
Object.assign(M["m4500_map"]["FI"],{"title":"Käyttöoikeus","free":"FREE-analyysejä jäljellä","email":"Käyttöoikeuden sähköposti","until":"Voimassa asti","none":"Ei yhdistetty","active":"Käyttöoikeus aktiivinen","freeMode":"FREE-tila","locked":"FREE-raja käytetty","switchBtn":"Tarkista käyttöoikeus tai käytä toista sähköpostia","disconnect":"Irrota sähköposti tältä laitteelta","note":"Sähköpostin vaihtaminen tai irrottaminen ei poista tiliä tai palvelimen käyttöoikeutta.","emailTitle":"Anna käyttöoikeuden sähköposti","emailText":"Anna sähköposti, jota haluat käyttää tai tarkistaa.","notActive":"Tälle sähköpostille ei löytynyt aktiivista käyttöoikeutta.","disconnected":"Sähköposti irrotettiin vain tältä laitteelta.","disconnectTitle":"Irrotetaanko sähköposti?","disconnectText":"Tämä sähköposti poistetaan vain tältä laitteelta. Tili ja aktiivinen käyttöoikeus säilyvät palvelimella."});
Object.assign(M["m5186_map"]["FI"],{"takePhoto":"Ota valokuva","chooseGallery":"Valitse galleriasta","flow1Title":"1. Mitä se tarkoittaa?","flow1Text":"Selittää asiakirjan yksinkertaisesti.","flow2Title":"2. Mitä nyt?","flow2Text":"Näyttää seuraavan vaiheen.","flow3Title":"3. Onko se turvallinen?","flow3Text":"Tarkistaa huijausriskin."});
M["m5319_map"]["FI"]="Jokainen asiakirja. Jokainen kieli. Selkeä selitys, analyysi ja vastaus.";
M["m5334_map"]["FI"]=["Ymmärrä kirje","Tiedä mitä tehdä seuraavaksi","Tarkista, vaikuttaako se turvalliselta","Valmiit vastausesimerkit"];
Object.assign(M["m5464_packs"]["FI"],{"free":"ILMAINEN — jäljellä","basic":"BASIC — jäljellä","pro":"PRO — jäljellä"});
Object.assign(M["m5491_map"]["FI"],{"title":"Uudet AI-työkalut","desc":"Kokeile mitä tahansa uutta työkalua 2 kertaa. Avaa sitten Premium-paketti.","trials":"Kokeilukerrat:","premium":"BASIC: 2 käyttöä • PRO: 100 käyttöä","badge":"AI-työkalu","screenshotTitle":"Tarkista kuvakaappaus","screenshotDesc":"Viesti, mainos, varoitus tai epäilyttävä näyttö.","linkTitle":"Tarkista linkki tai verkkosivusto","linkDesc":"Verkkotunnuksen, esiintymisen ja riskisignaalien tarkistus.","messageTitle":"Tarkista sähköposti tai SMS","messageDesc":"Viesti yritykseltä, virastolta, pankilta tai tuntemattomalta lähettäjältä.","replyTitle":"Vastausavustaja","replyDesc":"Kohtelias, napakka tai neutraali vastaus muokattavaksi.","conversationTitle":"Valmistaudu keskusteluun","conversationDesc":"Kysymyksiä ja lauseita virastoa, yritystä tai laitosta varten.","note":"Valitse työkalu, syötä sisältö ja käytä yksi kahdesta kokeilustasi.","used":"Kokeilukerta merkitty. Täysi toiminto yhdistetään seuraavassa vaiheessa.","locked":"Kokeilukerrat on käytetty. Avaa Premium."});
Object.assign(M["m5581_pack"]["FI"],{"useTrial":"Käytä kokeilu","close":"Sulje","empty":"Syötä sisältö testin suorittamiseksi."});
Object.assign(M["m5699_map"]["FI"],{"empty":"Syötä sisältö testin suorittamiseksi.","loading":"Analysoidaan…","what":"Mikä se on","risk":"Riski","next":"Mitä tehdä seuraavaksi","reply":"Ehdotus","low":"Matala","medium":"Keskitaso","high":"Korkea"});
Object.assign(M["m5871_labels"]["FI"],{"flow":"ℹ️ Miten analyysi toimii?","info":"ℹ️ Tiedot ja yksityisyys"});
Object.assign(M["m6294_map"]["FI"],{"button":"📄 Uusi analyysi","help":"Aloita toisen kirjeen analysointi.","toast":"✅ Valmis! Voit analysoida seuraavan kirjeen."});
Object.assign(M["m6479_dict"]["FI"],{"fraudRiskTitle":"Huijausriskin analyysi","separatorText":"Sense Bridge -arvio ja toimenpiteet","fraudUnknown":"Aitoutta ei voida arvioida","fraudLow":"Vaikuttaa melko uskottavalta","fraudMedium":"Tarkista lähettäjä","fraudHigh":"Korkea huijausriski","fraudDisclaimer":"Tämä on riskianalyysi, ei vahvistus asiakirjan aitoudesta.","confidence":"Varmuus","signals":"Tarkistettavat merkit","suspicious":"Epäilyttävät osat","safeSteps":"Turvalliset vaiheet","country":"Maa","officialWebsite":"Virallinen verkkosivusto","verifyInstitution":"Tarkista tilanne laitoksen viralliselta verkkosivustolta.","recognitionConfidence":"Tunnistuksen varmuus","legalNone":"Oikeudellista apua ei tarvita","legalRecommended":"Tilanteesta voi olla hyvä kysyä neuvoa","legalUrgent":"Kiireellinen oikeudellinen apu voi olla tarpeen","urgencyHigh":"KIIREELLINEN – nopea toiminta tarvitaan","urgencyMedium":"KESKITASON KIIREELLISYYS – kannattaa reagoida","urgencyLow":"MATALA KIIREELLISYYS – voit tarkistaa rauhassa","replyNeutral":"NEUTRAALI","replyPolite":"KOHTELIAS","replyFirm":"NAPAKKA","examplesDocFallback":"Vastausta asiakirjan kielellä ei voitu luoda automaattisesti. Valitse asiakirjan kieli käsin AUTO-valinnan sijaan ja yritä uudelleen."});
M["m8450_labels"]["FI"]="Sense Bridge -arvio ja toimenpiteet";
Object.assign(M["m8484_COPY"]["FI"],{"label":"Sovellusnäkymä","sub":"Valitse yksinkertainen tai täysi näkymä","simple":"Yksinkertainen","full":"Täysi","language":"Sovelluksesi kieli","show":"📂 Näytä koko analyysi","hide":"📁 Piilota tiedot"});
M["m8495_FLAGS"]["FI"]="🇫🇮 FI";
Object.assign(M["m8598_COPY"]["FI"],{"menu":"Valikko","title":"Sense Bridge -valikko","ai":"Uudet AI-työkalut","aiSub":"Tarkista kuvakaappaus, linkki, viesti tai valmistele vastaus.","view":"Sovellusnäkymä","viewSub":"Vaihda yksinkertaisen ja täyden näkymän välillä.","benefits":"Mitä sovellus tekee","benefitsSub":"Katso Sense Bridgen tärkeimmät ominaisuudet.","access":"Käyttöoikeus","accessSub":"Tarkista FREE-analyysit tai aktiivinen käyttöoikeus.","note":"Täydessä näkymässä kaikki osiot ovat aina näkyvissä.","close":"Sulje"});
Object.assign(M["m9112_SB_UX_COPY"]["FI"],{"main":"Jokainen asiakirja. Jokainen kieli.","sub":"Selkeä selitys, analyysi ja vastaus.","more":"Lisää","moreTitle":"Lisää vaihtoehtoja","install":"Asenna sovellus","placeholder":"Liitä kirjeen tai sähköpostin teksti tähän…"});
M["m9112_SB_UX_COPY"]["FI"].free=n=>`${n} ilmaista analyysiä jäljellä`;M["m9112_SB_UX_COPY"]["FI"].active=s=>`Käyttöoikeus aktiivinen: ${s}`;
Object.assign(M["m9206_SB_EXTRA_COPY"]["FI"],{"reach":"100+ kieltä — ymmärrä asiakirja omalla kielelläsi"});
Object.assign(M["m9695_COMMON"]["FI"],{"text":"📝 Liitä teksti","upload":"🖼️ Lisää tiedosto","take":"📷 Ota valokuva","gallery":"🖼️ Valitse galleriasta","pdf":"📄 Valitse PDF","clear":"Tyhjennä","close":"Sulje","none":"Tiedostoa ei valittu.","maxImages":"Voit lisätä enintään 5 kuvaa.","maxPdf":"PDF voi sisältää enintään 10 sivua tässä testiversiossa.","empty":"Liitä teksti tai lisää tiedosto.","extracting":"Luetaan PDF:ää…","analyzing":"Analysoidaan…","done":"Analyysi on valmis.","error":"Analyysiä ei voitu suorittaa.","locked":"Ilmaiset AI-kokeilut on käytetty. Aktivoi Premium.","pdfLoad":"PDF-lukijaa ei voitu käynnistää. Tarkista internetyhteys."});
Object.assign(M["m9959_COPY"]["FI"],{"analysis":"Analyysi","tools":"AI-työkalut","settings":"Asetukset"});
Object.assign(M["ui_main"]["FI"],{"title":"Sense Bridge","desc":"Viralliset kirjeet selitettynä omalla kielelläsi. Ei neuvontaa. Ei painostusta. Vain selkeästi.","paste":"Liitä kirje","photoTitle":"Kirjeen kuva","choosePhoto":"Valitse kuva","noPhoto":"Kuvaa ei ole valittu","readPhoto":"Lue teksti kuvasta","placeholder":"👇 Napauta tästä ja liitä kirjeen tai sähköpostin sisältö…","btnAnalyze":"Analysoi kirje","userLang":"Oma kielesi","sourceLangLabel":"Asiakirjan kieli","installApp":"📱 Lisää Sense Bridge puhelimeesi","fraudInfoTitle":"🛡️ Asiakirjan turvallisuustarkistus","translation":"Käännös","summary":"Mitä viranomainen kertoo","risks":"Viestinnän riskit","examples":"Vastausesimerkit","free":"FREE:","analyses":"analyysiä","access":"Käyttöoikeus:","srcAuto":"🌐 AUTO","clear":"Tyhjennä","copyTr":"Kopioi käännös","footerPrivacy":"Yksityisyys","footerTerms":"Ehdot","footerContact":"Yhteystiedot","analyzingLetter":"Analysoidaan kirjettä…"});
M["m6857_langMap"]=M["m6857_langMap"]||Object.create(null);M["m6857_langMap"]["FI"]="FI";

/* Nordic completeness patch — UI text only. */
Object.assign(M["m7463_SB_UX_V10_TEXT"]["FI"],{progressTitle:"Asiakirjan analyysi",progress1:"Valmistellaan",progress2:"Luetaan teksti",progress3:"Sisällön analyysi",progress4:"Turvallisuustarkistus",progress5:"Valmis",statusPreparing:"Valmistellaan analyysiä...",statusReading:"Luetaan asiakirjaa...",statusAnalyzing:"Analysoidaan sisältöä...",statusSafety:"Tarkistetaan turvallisuutta...",statusDone:"Valmis – katso alta",statusError:"Analyysivirhe",quickTitle:"✨ Lyhyt yhteenveto",quickMeaning:"📝 Mitä tämä tarkoittaa?",quickAction:"⚠️ Pitääkö minun toimia?",quickSafety:"🛡️ Onko tämä turvallinen?",noShortSummary:"Lyhyttä yhteenvetoa ei ole saatavilla. Katso tiedot alta.",noAction:"Selkeää toimenpidettä ei havaittu. Tarkista analyysin tiedot.",lowUrgency:"Matala kiireellisyys",mediumUrgency:"Keskitasoinen kiireellisyys",highUrgency:"Kiireellinen",unknownUrgency:"Ei määritetty",safeLow:"Vaikuttaa melko turvalliselta",safeMedium:"Kannattaa tarkistaa",safeHigh:"Korkea riski",safeUnknown:"Ei voida arvioida",printPdf:"📄 Lataa / tallenna PDF",printHint:"Tallenna tulos PDF-tiedostoksi puhelimen tulostustoiminnolla."});
Object.assign(M["m9206_SB_EXTRA_COPY"]["FI"],{takeScreenshot:"Ota kuva näytöstä",chooseScreenshot:"Valitse galleriasta",noScreenshot:"Kuvaa ei ole valittu"});
Object.assign(M["ui_main"]["FI"],{fraudInfoText:"Analyysin jälkeen Sense Bridge tarkistaa myös mahdollisen huijausriskin, laitoksen jäljittelyn ja asiakirjan epäilyttävät osat.",installHelp:"Lisää sovelluksen pikakuvake puhelimeesi:\\n\\nNapauta selaimen kolmea pistettä\\n→ Lisää aloitusnäyttöön",free:"ILMAINEN:",reset:"Nollaa testi",lock:"Ilmainen rajasi on käytetty. Valitse käyttöoikeus alta jatkaaksesi.",examplesUser:"Vastausesimerkit (omalla kielelläsi)",examplesDoc:"Vastausesimerkit (asiakirjan kielellä)",copyExDoc:"Kopioi lähetettävä vastaus",examplesDocEmpty:"Analyysin jälkeen tähän ilmestyy vastaus asiakirjan kielellä.",payTitle:"Käyttöoikeus ilman tilausta",payDesc:"Saat ensin 3 ilmaista analyysiä kokeiluun. Valitse sitten sopiva käyttöaika.",p24meta:"Pääsy analyyseihin 24 tunnin ajan",p7meta:"Useita viestejä varten",p30meta:"Rauhaa koko kuukaudeksi",p7name:"7 päivää",p30name:"30 päivää",best:"Paras vaihtoehto",fine1:"Sense Bridge ei anna oikeudellista neuvontaa. Se auttaa ymmärtämään merkityksen, sävyn ja riskit, jotta voit päättää itse.",fine2:"Tarjoamme selkeyttä ja mielenrauhaa, emme pelkkää ‘AI:ta’.",hintUI:"‘UI’ tarkoittaa vain sivun kieltä (painikkeet ja otsikot) – se ei muuta analyysiä.",privacyNote:"<strong>Yksityisyys:</strong> Asiakirjoja ei tallenneta julkisesti eikä jaeta. Liitä vain sisältö, jonka haluat analysoida.",footerDefault:"Sense Bridge on tiedollinen palvelu eikä asianajotoimisto.",footerPrivacyText:"Yksityisyys: emme julkaise käyttäjien asiakirjoja. Teknisiä tietoja ja käyttöoikeustietoja käytetään vain palvelun toimintaan.",footerTermsText:"Ehdot: käyttäjä vastaa lisäämästään sisällöstä. Analyysi on tiedollinen eikä oikeudellista neuvontaa.",footerContactText:"Yhteystiedot: käyttöoikeus- tai maksuongelmissa käytä Sense Bridgen ilmoittamaa yhteysosoitetta.",helpLinksTitle:"Hyödylliset linkit",copyEx:"Kopioi vastaukset (omalla kielelläni)"});
Object.assign(M["m6113_t"]["FI"],{lead:"Käytä Sense Bridgeä tavallisen sovelluksen tavoin.",hint:"Napauta selaimen kolmen pisteen valikkoa ja valitse ‘Lisää aloitusnäyttöön’."});
Object.assign(M["m6138_map"]["FI"],{title:"Osta käyttöoikeus",amount:"Summa:",transfer:"Maksa pankkisiirrolla:",receiver:"Saaja:",transferTitle:"Maksun viite/otsikko:",paid:"✔ Olen maksanut",saved:"✅ Pyyntö tallennettu",savedText:"Kiitos. Tee pankkisiirto käyttäen täsmälleen alla olevaa maksun otsikkoa. Käyttöoikeus aktivoidaan maksun manuaalisen vahvistuksen jälkeen.",copy:"Kopioi maksun otsikko",small:"Kun maksu on vastaanotettu, aktivoimme käyttöoikeuden. Voit palata myöhemmin ja tarkistaa käyttöoikeuden samalla sähköpostiosoitteella."});
Object.assign(M["m7072_txt"]["FI"],{emailTitle:"Anna sähköpostiosoitteesi",emailText:"Liitämme maksupyynnön ja käyttöoikeuden tähän osoitteeseen.",copied:"Kopioitu ✔",copiedText:"Maksun otsikko on kopioitu.",noEmail:"Anna ensin sähköpostiosoitteesi.",noPlan:"Pakettia ei ole valittu.",blocked:"Tämä sähköpostiosoite on estetty.",error:"Virhe: ",activationError:"Aktivointivirhe",pendingTitle:"Pyyntö tallennettu ✔",pendingText:"Tee siirto annetulla otsikolla. Käyttöoikeus aktivoidaan maksun vahvistuksen jälkeen."});
Object.assign(M["m6799_dict"]["FI"],{recognizedInstitution:"Tunnistettu laitos",countryFromDocument:"Asiakirjan maa",probableCountry:"Todennäköinen maakonteksti",countryNotCertain:"Laitoksen maata ei voitu vahvistaa selvästi asiakirjan tekstistä.",basedOnContent:"asiakirjan tekstin/linkkien perusteella",basedOnLanguage:"asiakirjan kielen perusteella – tämä on vain vihje",websiteHidden:"Yhtä kansallista verkkosivustoa ei näytetä varmana, koska maata ei ole vahvistettu riittävästi.",safeInstitutionStep:"Älä napsauta viestin linkkejä. Avaa virallinen sovellus tai etsi laitos itse.",officialWebsiteShown:"Verkkosivusto näytetään vain, jos se ei ole ristiriidassa asiakirjan kontekstin kanssa."});
Object.assign(M["m7375_dict"]["FI"],{HIGH:"🚨 Korkea huijausriski. Älä napsauta linkkejä; tarkista asia virallisen kanavan kautta.",MEDIUM:"⚠️ Asiakirja vaatii huolellisen tarkistuksen. Tarkista lähettäjä, linkit ja määräaika viralliselta verkkosivustolta.",LOW:"✅ Vahvoja huijausmerkkejä ei havaittu. Tarkista silti asiakirjan tiedot.",UNKNOWN:"ℹ️ Asiakirjan turvallisuutta ei voida arvioida selvästi. Tarkista lähettäjä virallisen kanavan kautta."});
Object.assign(M["m6039_map"]["FI"],{name:"30 päivää PRO",meta:"Täysi käyttöoikeus + kehittyneet AI-työkalut",features:"100 AI-työkalun käyttökertaa 30 päivän ajan sekä täysi tavallisen analyysin käyttö.",aria:"Valitse 30 päivän PRO-käyttöoikeus 25 eurolla"});
Object.assign(M["m5581_pack"]["FI"].previewDesc,{screenshot:"Kuvaile epäilyttävä näyttö, viesti, mainos tai varoitus.",link:"Liitä tarkistettava linkki tai verkkosivuston osoite.",message:"Liitä sähköpostin, SMS-viestin tai muun viestin sisältö.",reply:"Liitä viesti tai kirje, johon haluat vastata.",conversation:"Kuvaile, kenen kanssa keskustelet ja mistä asiassa on kyse."});
Object.assign(M["m5581_pack"]["FI"].placeholder,{screenshot:"Esim. virusvaroitus, maksupyyntö, ponnahdusmainos...",link:"Liitä linkki tähän, esim. https://...",message:"Liitä viestin sisältö...",reply:"Liitä kirjeen tai viestin sisältö...",conversation:"Esim. virasto-, pankki-, työnantaja- tai koulukeskustelu..."});


Object.assign(M["m9439_COPY"]["FI"],{tool:"Sopimusanalyysi",toolDesc:"Keskeiset ehdot, velvoitteet, määräajat ja huomiota vaativat kohdat.",title:"Sopimusanalyysi",desc:"Liitä sopimuksen teksti tai lisää enintään 5 kuvaa peräkkäisistä sivuista.",textTab:"📝 Liitä teksti",imagesTab:"🖼️ Lisää kuvia",placeholder:"Liitä sopimuksen teksti tähän...",camera:"📷 Ota valokuva",gallery:"🖼️ Valitse galleriasta",note:"Sense Bridge korostaa tärkeitä ehtoja ja mahdollisia riskejä. Tämä on tiedollista AI-ohjausta, ei oikeudellista neuvontaa.",run:"Analysoi sopimus",clear:"Tyhjennä",close:"Sulje",empty:"Liitä sopimuksen teksti tai lisää vähintään yksi kuva.",tooMany:"Voit lisätä enintään 5 kuvaa.",analyzing:"Analysoidaan sopimusta...",done:"Sopimusanalyysi on valmis.",error:"Sopimusta ei voitu analysoida.",locked:"Ilmaiset AI-kokeilut on käytetty. Aktivoi Premium.",overview:"📋 Millainen sopimus tämä on ja mitä se koskee",duties:"✅ Velvoitteet ja keskeiset ehdot",dates:"📅 Määräajat, irtisanominen ja uusiminen",risks:"⚠️ Huomiota vaativat ehdot",next:"➡️ Mitä tarkistaa tai tehdä seuraavaksi",plain:"🌍 Selkokielinen selitys / käännös"});
Object.assign(M["m9707_TOOLS"]["FI"],{pdf:{title:"PDF-analyysi",desc:"Lisää enintään 10-sivuinen PDF. Sense Bridge poimii tekstin ja lähettää skannatut sivut OCR-tunnistukseen.",card:"Lue ja selitä monisivuinen PDF-asiakirja.",run:"Analysoi PDF",placeholder:"Voit myös liittää tekstin PDF-asiakirjasta...",note:"Testiversio: enintään 10 sivua. Asiakirjoja ei tallenneta.",labels:["📋 Mikä tämä asiakirja on","🏛️ Lähettäjä ja tarkoitus","📅 Määräajat ja päivämäärät","⚠️ Tärkeät tai epäselvät kohdat","➡️ Mitä tehdä seuraavaksi","🌍 Selkokielinen selitys"]},form:{title:"Lomakeapu",desc:"Liitä lomake tai lisää enintään 5 kuvaa peräkkäisistä sivuista.",card:"Kenttien, vaadittujen tietojen ja asiakirjojen selitys.",run:"Selitä lomake",placeholder:"Liitä lomakkeen teksti tai kuvaile, missä tarvitset apua...",note:"Sense Bridge selittää kentät, mutta ei syötä tietojasi eikä lähetä lomaketta.",labels:["📋 Lomakkeen tarkoitus","📝 Kenttien täyttäminen","📎 Vaaditut tiedot ja asiakirjat","⚠️ Huomiota vaativat kentät","➡️ Seuraavat vaiheet","🌍 Selkokielinen selitys"]},photo:{title:"Kuva-analyysi",desc:"Lisää enintään 5 kuvaa, joissa on tekstiä, ilmoitus, kyltti tai asiakirja.",card:"Lue ja selitä kuvissa näkyvä teksti.",run:"Analysoi kuvat",placeholder:"Voit halutessasi kuvailla kuvaa tai kertoa, mitä haluat tietää...",note:"Kuvan tulee olla terävä, hyvin valaistu ja sisältää koko tekstin.",labels:["🖼️ Mitä kuvissa näkyy","📄 Poimittu sisältö","🏛️ Lähettäjä tai lähde","⚠️ Tärkeät merkit","➡️ Mitä tehdä seuraavaksi","🌍 Selkokielinen selitys / käännös"]},bill:{title:"Laskut",desc:"Liitä laskun teksti tai lisää enintään 5 kuvaa sen sivuista.",card:"Summat, maksupäivät, rivit ja mahdolliset epäselvät veloitukset.",run:"Selitä lasku",placeholder:"Liitä laskun teksti...",note:"Sense Bridge antaa tiedollista ohjausta. Tarkista saaja ja pankkitiedot ennen maksamista.",labels:["🧾 Mistä laskussa on kyse","💶 Summat ja rivit","📅 Maksupäivä ja maksutapa","⚠️ Veloitukset tai epäselvät kohdat","➡️ Mitä tarkistaa ennen maksamista","🌍 Selkokielinen selitys"]}});

Object.assign(M["m5723_copy"]["FI"],{screenshot:{what:"Tämä näyttää näytöltä tai varoitukselta, joka kannattaa tarkistaa.",next:"Älä paina painikkeita tai linkkejä ennen kuin olet tarkistanut lähteen. Vertaa tietoja viralliseen verkkosivustoon.",reply:"Jos viesti väittää olevansa laitokselta, avaa virallinen sivusto itse."},link:{what:"Tämä on tarkistettava linkki tai verkkosivuston osoite.",next:"Tarkista verkkotunnus itse. Älä kirjaudu sisään viestin linkin kautta. Avaa virallinen verkkosivusto itse.",reply:"On turvallisempaa avata virallinen sivusto haun tai tallennetun kirjanmerkin kautta."},message:{what:"Tämä viesti kannattaa tarkistaa tietojenkalastelun tai painostuksen varalta.",next:"Tarkista lähettäjä, verkkotunnus ja mahdollinen kiireeseen painostaminen. Älä jaa kirjautumistietoja.",reply:"Kiitos viestistä. Tarkistan asian virallisen yhteydenottokanavan kautta."},reply:{what:"Tähän tilanteeseen voidaan valmistella rauhallinen vastaus.",next:"Vastaa lyhyesti ja selkeästi ilman tarpeettomia henkilötietoja.",reply:"Kiitos viestistä. Selittäisittekö asian ja mitä minun tulee tehdä?"},conversation:{what:"Tähän keskusteluun kannattaa valmistautua etukäteen.",next:"Kirjoita ylös tavoite, mukaan otettavat asiakirjat ja 2–3 kysymystä.",reply:"Haluaisin selvittää asian rauhallisesti. Kertoisitteko seuraavat vaiheet ja tarvittavat asiakirjat?"}});

})(window);

// Nordic install dialog
window.SB_INSTALL_I18N = window.SB_INSTALL_I18N || {};
window.SB_INSTALL_I18N.FI = {
  title: "Lisää Sense Bridge<br>puhelimeesi",
  text: "Pidä Sense Bridge aina käden ulottuvilla.",
  privacy: "Kirjeitäsi ja kuviasi ei tallenneta eikä jaeta.",
  step: "Napauta selaimen <b>kolmen pisteen</b> valikkoa ja valitse:",
  add: "Lisää aloitusnäyttöön",
  ok: "Selvä"
};

/* Nordic full-message audit patch v4 — function-valued UI strings only. */
(function(w){"use strict";const M=w.SB_I18N&&w.SB_I18N.modules;if(!M)return;
if(M["m9439_COPY"]&&M["m9439_COPY"].FI){M["m9439_COPY"].FI.count=n=>`Valittu: ${n}/5`;M["m9439_COPY"].FI.reading=(i,n)=>`Luetaan sivua ${i}/${n}...`;}
if(M["m9695_COMMON"]&&M["m9695_COMMON"].FI){M["m9695_COMMON"].FI.selected=n=>`Valittu: ${n}/5`;M["m9695_COMMON"].FI.reading=(i,n)=>`Luetaan sivua ${i}/${n}...`;}
})(window);
