/* Sense Bridge V2 — HU. Safe extension: clone EN defaults, then override translated UI. */
(function(w){
  "use strict";
  const R=(w.SB_I18N=w.SB_I18N||{modules:Object.create(null)});
  const M=R.modules;
  function clone(v){
    if(Array.isArray(v)) return v.map(clone);
    if(v && typeof v==="object"){const o={};Object.keys(v).forEach(k=>o[k]=clone(v[k]));return o;}
    return v;
  }
  Object.keys(M).forEach(id=>{ if(M[id] && M[id].EN!==undefined && M[id]["HU"]===undefined) M[id]["HU"]=clone(M[id].EN); });
  const ui=M["ui_main"]["HU"]; Object.assign(ui,{"title":"Sense Bridge","desc":"Hivatalos levelek elmagyarázva az Ön nyelvén. Nincs tanácsadás. Nincs nyomás. Csak érthetően.","paste":"Illessze be a levelet","photoTitle":"Levél fotója","choosePhoto":"Fotó kiválasztása","noPhoto":"Nincs fotó kiválasztva","readPhoto":"Szöveg beolvasása fotóról","placeholder":"👇 Koppintson ide, és illessze be a levél vagy e-mail tartalmát…","btnAnalyze":"Levél elemzése","userLang":"Az Ön nyelve","sourceLangLabel":"Dokumentum nyelve","fraudInfoTitle":"🛡️ Dokumentumbiztonsági ellenőrzés","fraudInfoText":"Az elemzés után a Sense Bridge ellenőrzi a lehetséges csalási kockázatot, az intézménynek való kiadást és a dokumentum gyanús elemeit is.","installApp":"📱 Sense Bridge hozzáadása a telefonhoz","free":"INGYENES:","analyses":"elemzés","access":"Hozzáférés:","reset":"Teszt visszaállítása","lock":"Az ingyenes keret elfogyott. A folytatáshoz válasszon hozzáférést lent.","translation":"Fordítás","summary":"Mit közöl a hivatal","risks":"Kommunikációs kockázatok","examples":"Válaszpéldák","examplesUser":"Válaszpéldák (az Ön nyelvén)","examplesDoc":"Válaszpéldák (a dokumentum nyelvén)","copyExDoc":"Küldhető válasz másolása","payTitle":"Előfizetés nélküli hozzáférés","payDesc":"Kipróbálásra 3 INGYENES elemzést kap. Ezután válasszon kényelmes hozzáférési időszakot.","p24meta":"Hozzáférés az elemzésekhez 24 órán át","p7meta":"Több üzenethez","p30meta":"Nyugalom egy egész hónapra","p7name":"7 nap","p30name":"30 nap","best":"Legjobb ár-érték","fine1":"A Sense Bridge nem nyújt jogi tanácsadást. Segít megérteni a jelentést, a hangnemet és a kockázatokat, hogy Ön dönthessen.","fine2":"Nyugalmat és megértést kínálunk, nem „AI-t“.","hintUI":"A „UI“ egyszerűen az oldal nyelve (gombok és címkék); nem változtatja meg az elemzést.","privacyNote":"<strong>Adatvédelem:</strong> A dokumentumokat nem tároljuk vagy osztjuk meg nyilvánosan. Csak azt illessze be, amit elemezni szeretne.","footerPrivacy":"Adatvédelem","footerTerms":"Feltételek","footerContact":"Kapcsolat","footerDefault":"A Sense Bridge tájékoztató eszköz, nem ügyvédi iroda.","analyzingLetter":"Levél elemzése…","helpLinksTitle":"Hasznos linkek","srcAuto":"🌐 AUTO","clear":"Adatok törlése elemzés után","copyTr":"Fordítás másolása","copyEx":"Válaszok másolása (saját nyelven)"});
  Object.assign(M["m9112_SB_UX_COPY"]["HU"],{"main":"Minden dokumentum. Minden nyelv.","sub":"Világos magyarázat, elemzés és válasz.","more":"Továbbiak","moreTitle":"További lehetőségek","install":"Alkalmazás telepítése","placeholder":"Illessze be ide a levél vagy e-mail szövegét…"});
  Object.assign(M["m8484_COPY"]["HU"],{"label":"Alkalmazásnézet","sub":"Válasszon egyszerű vagy teljes nézetet","simple":"Egyszerű","full":"Teljes","language":"Az alkalmazás nyelve","show":"📂 Teljes elemzés megjelenítése","hide":"📁 Részletek elrejtése"});
  M["m8495_FLAGS"]["HU"]="🇭🇺 HU";
  M["m6857_langMap"]=M["m6857_langMap"]||Object.create(null); M["m6857_langMap"]["HU"]="HU";
  Object.assign(M["m9959_COPY"]["HU"],{"analysis":"Elemzés","tools":"AI-eszközök","settings":"Beállítások"});
  Object.assign(M["m9695_COMMON"]["HU"],{"text":"📝 Szöveg beillesztése","upload":"🖼️ Fájl hozzáadása","take":"📷 Fotó készítése","gallery":"🖼️ Választás a galériából","pdf":"📄 PDF kiválasztása","clear":"Törlés","close":"Bezárás","none":"Nincs fájl kiválasztva.","empty":"Illesszen be szöveget vagy adjon hozzá fájlt.","extracting":"PDF olvasása…","analyzing":"Elemzés…","done":"Az elemzés elkészült.","error":"Az elemzés nem hajtható végre."});
  Object.assign(M["m4367_labels"]["HU"],{"light":"☀️ Világos","dark":"🌙 Sötét"});
  Object.assign(M["m5186_map"]["HU"],{"takePhoto":"Fotó készítése","chooseGallery":"Választás a galériából","flow1Title":"1. Mit jelent?","flow1Text":"Egyszerűen elmagyarázza a dokumentumot.","flow2Title":"2. Mit tegyek most?","flow2Text":"Megmutatja a következő lépést.","flow3Title":"3. Biztonságos?","flow3Text":"Ellenőrzi a csalás kockázatát."});
  M["m5319_map"]["HU"]="Minden dokumentum. Minden nyelv. Világos magyarázat, elemzés és válasz.";
  M["m5334_map"]["HU"]=["Értse meg a levelet","Tudja, mi a következő lépés","Ellenőrizze, hogy biztonságosnak tűnik-e","Kész válaszpéldák"];
  Object.assign(M["m5871_labels"]["HU"],{"flow":"ℹ️ Hogyan működik az elemzés?","info":"ℹ️ Információ és adatvédelem"});
  Object.assign(M["m6294_map"]["HU"],{"button":"📄 Új elemzés","help":"Kezdje el egy másik levél elemzését.","toast":"✅ Kész! Elemezhet egy másik levelet."});
  M["m8450_labels"]["HU"]="Sense Bridge értékelés és lépések";
  Object.assign(M["m9206_SB_EXTRA_COPY"]["HU"],{"reach":"100+ nyelv — értse meg a dokumentumot a saját nyelvén","takeScreenshot":"Képernyő fotózása","chooseScreenshot":"Választás a galériából","noScreenshot":"Nincs kép kiválasztva"});
  Object.assign(M["m5491_map"]["HU"],{"title":"Új AI-eszközök","desc":"Próbáljon ki bármely új eszközt 2 alkalommal. Ezután oldja fel a Premium csomagot.","trials":"Próbahasználatok:","badge":"AI-eszköz","screenshotTitle":"Képernyőkép ellenőrzése","screenshotDesc":"Üzenet, hirdetés, figyelmeztetés vagy gyanús képernyő.","linkTitle":"Link vagy webhely ellenőrzése","linkDesc":"Domain-, megszemélyesítés- és kockázati jelzés ellenőrzése.","messageTitle":"E-mail vagy SMS ellenőrzése","messageDesc":"Üzenet cégtől, hivataltól, banktól vagy ismeretlen feladótól.","replyTitle":"Válaszasszisztens","replyDesc":"Udvarias, határozott vagy semleges válasz további szerkesztéshez.","conversationTitle":"Felkészülés beszélgetésre","conversationDesc":"Kérdések és mondatok hivatalhoz, céghez vagy intézményhez.","note":"Válasszon eszközt, adja meg a tartalmat, és használja fel a 2 próba egyikét.","locked":"A próbahasználatok elfogytak. Oldja fel a Premium csomagot."});
})(window);
