/* Sense Bridge V2 — LT. Safe extension: clone EN defaults, then override translated UI. */
(function(w){
  "use strict";
  const R=(w.SB_I18N=w.SB_I18N||{modules:Object.create(null)});
  const M=R.modules;
  function clone(v){
    if(Array.isArray(v)) return v.map(clone);
    if(v && typeof v==="object"){const o={};Object.keys(v).forEach(k=>o[k]=clone(v[k]));return o;}
    return v;
  }
  Object.keys(M).forEach(id=>{ if(M[id] && M[id].EN!==undefined && M[id]["LT"]===undefined) M[id]["LT"]=clone(M[id].EN); });
  const ui=M["ui_main"]["LT"]; Object.assign(ui,{"title":"Sense Bridge","desc":"Oficialūs laiškai paaiškinti jūsų kalba. Be patarimų. Be spaudimo. Tiesiog aiškiai.","paste":"Įklijuokite laišką","photoTitle":"Laiško nuotrauka","choosePhoto":"Pasirinkti nuotrauką","noPhoto":"Nuotrauka nepasirinkta","readPhoto":"Nuskaityti tekstą iš nuotraukos","placeholder":"👇 Bakstelėkite čia ir įklijuokite laiško ar el. laiško turinį…","btnAnalyze":"Analizuoti laišką","userLang":"Jūsų kalba","sourceLangLabel":"Dokumento kalba","fraudInfoTitle":"🛡️ Dokumento saugumo patikra","fraudInfoText":"Po analizės Sense Bridge taip pat patikrins galimą sukčiavimo riziką, apsimetimą institucija ir įtartinus dokumento elementus.","installApp":"📱 Pridėti Sense Bridge į telefoną","free":"NEMOKAMAI:","analyses":"analizės","access":"Prieiga:","reset":"Bandomasis atstatymas","lock":"Nemokamas limitas išnaudotas. Norėdami tęsti, pasirinkite prieigą žemiau.","translation":"Vertimas","summary":"Ką praneša institucija","risks":"Bendravimo rizikos","examples":"Atsakymų pavyzdžiai","examplesUser":"Atsakymų pavyzdžiai (jūsų kalba)","examplesDoc":"Atsakymų pavyzdžiai (dokumento kalba)","copyExDoc":"Kopijuoti siunčiamą atsakymą","payTitle":"Prieiga be prenumeratos","payDesc":"Išbandymui gaunate 3 NEMOKAMAS analizes. Tada pasirinkite patogų prieigos laikotarpį.","p24meta":"Vienam skubiam laiškui","p7meta":"Keliems pranešimams","p30meta":"Ramybė visam mėnesiui","p7name":"7 dienos","p30name":"30 dienų","best":"Geriausia vertė","fine1":"Sense Bridge neteikia teisinių konsultacijų. Ji padeda suprasti prasmę, toną ir riziką, kad galėtumėte nuspręsti patys.","fine2":"Mes siūlome ramybę ir supratimą, o ne „AI“.","hintUI":"„UI“ – tai tiesiog puslapio kalba (mygtukai ir etiketės); ji nekeičia analizės.","privacyNote":"<strong>Privatumas:</strong> Dokumentai nėra viešai saugomi ar bendrinami. Įklijuokite tik tai, ką norite analizuoti.","footerPrivacy":"Privatumas","footerTerms":"Sąlygos","footerContact":"Kontaktai","footerDefault":"Sense Bridge yra informacinė priemonė ir nėra advokatų kontora.","analyzingLetter":"Analizuojamas laiškas…","helpLinksTitle":"Naudingos nuorodos","srcAuto":"🌐 AUTO","clear":"Išvalyti duomenis po analizės","copyTr":"Kopijuoti vertimą","copyEx":"Kopijuoti atsakymus (mano kalba)"});
  Object.assign(M["m9112_SB_UX_COPY"]["LT"],{"main":"Kiekvienas dokumentas. Kiekviena kalba.","sub":"Aiškus paaiškinimas, analizė ir atsakymas.","more":"Daugiau","moreTitle":"Daugiau parinkčių","install":"Įdiegti programėlę","placeholder":"Įklijuokite čia laiško ar el. laiško tekstą…"});
  Object.assign(M["m8484_COPY"]["LT"],{"label":"Programėlės vaizdas","sub":"Pasirinkite paprastą arba pilną režimą","simple":"Paprastas","full":"Pilnas","language":"Jūsų programėlės kalba","show":"📂 Rodyti pilną analizę","hide":"📁 Slėpti išsamią informaciją"});
  M["m8495_FLAGS"]["LT"]="🇱🇹 LT";
  M["m6857_langMap"]=M["m6857_langMap"]||Object.create(null); M["m6857_langMap"]["LT"]="LT";
  Object.assign(M["m9959_COPY"]["LT"],{"analysis":"Analizė","tools":"AI įrankiai","settings":"Nustatymai"});
  Object.assign(M["m9695_COMMON"]["LT"],{"text":"📝 Įklijuoti tekstą","upload":"🖼️ Pridėti failą","take":"📷 Fotografuoti","gallery":"🖼️ Pasirinkti iš galerijos","pdf":"📄 Pasirinkti PDF","clear":"Išvalyti","close":"Uždaryti","none":"Failas nepasirinktas.","empty":"Įklijuokite tekstą arba pridėkite failą.","extracting":"Skaitomas PDF…","analyzing":"Analizuojama…","done":"Analizė paruošta.","error":"Analizės atlikti nepavyko."});
  Object.assign(M["m4367_labels"]["LT"],{"light":"☀️ Šviesus","dark":"🌙 Tamsus"});
  Object.assign(M["m5186_map"]["LT"],{"takePhoto":"Fotografuoti","chooseGallery":"Pasirinkti iš galerijos","flow1Title":"1. Ką tai reiškia?","flow1Text":"Paprastai paaiškina dokumentą.","flow2Title":"2. Ką daryti dabar?","flow2Text":"Parodo kitą žingsnį.","flow3Title":"3. Ar tai saugu?","flow3Text":"Patikrina sukčiavimo riziką."});
  M["m5319_map"]["LT"]="Kiekvienas dokumentas. Kiekviena kalba. Aiškus paaiškinimas, analizė ir atsakymas.";
  M["m5334_map"]["LT"]=["Supraskite laišką","Žinokite, ką daryti toliau","Patikrinkite, ar atrodo saugu","Paruošti atsakymų pavyzdžiai"];
  Object.assign(M["m5871_labels"]["LT"],{"flow":"ℹ️ Kaip veikia analizė?","info":"ℹ️ Informacija ir privatumas"});
  Object.assign(M["m6294_map"]["LT"],{"button":"📄 Nauja analizė","help":"Pradėkite analizuoti kitą laišką.","toast":"✅ Paruošta! Galite analizuoti kitą laišką."});
  M["m8450_labels"]["LT"]="Sense Bridge įvertinimas ir žingsniai";
  Object.assign(M["m9206_SB_EXTRA_COPY"]["LT"],{"reach":"100+ kalbų — supraskite dokumentą savo kalba","takeScreenshot":"Nufotografuoti ekraną","chooseScreenshot":"Pasirinkti iš galerijos","noScreenshot":"Vaizdas nepasirinktas"});
  Object.assign(M["m5491_map"]["LT"],{"title":"Nauji AI įrankiai","desc":"Išbandykite bet kurį naują įrankį 2 kartus. Tada atrakinkite Premium paketą.","trials":"Bandomieji naudojimai:","badge":"AI įrankis","screenshotTitle":"Patikrinti ekrano nuotrauką","screenshotDesc":"Žinutė, reklama, įspėjimas ar įtartinas ekranas.","linkTitle":"Patikrinti nuorodą ar svetainę","linkDesc":"Domeno, apsimetimo ir rizikos signalų patikra.","messageTitle":"Patikrinti el. laišką ar SMS","messageDesc":"Įmonės, institucijos, banko ar nežinomo siuntėjo žinutė.","replyTitle":"Atsakymo asistentas","replyDesc":"Mandagus, tvirtas arba neutralus atsakymas tolesniam redagavimui.","conversationTitle":"Pasiruošti pokalbiui","conversationDesc":"Klausimai ir frazės pokalbiui su institucija ar įmone.","note":"Pasirinkite įrankį, įveskite turinį ir naudokite vieną iš 2 bandymų.","locked":"Bandomieji naudojimai išnaudoti. Atrakinkite Premium paketą."});
})(window);
