/* Sense Bridge V2 — LV. Safe extension: clone EN defaults, then override translated UI. */
(function(w){
  "use strict";
  const R=(w.SB_I18N=w.SB_I18N||{modules:Object.create(null)});
  const M=R.modules;
  function clone(v){
    if(Array.isArray(v)) return v.map(clone);
    if(v && typeof v==="object"){const o={};Object.keys(v).forEach(k=>o[k]=clone(v[k]));return o;}
    return v;
  }
  Object.keys(M).forEach(id=>{ if(M[id] && M[id].EN!==undefined && M[id]["LV"]===undefined) M[id]["LV"]=clone(M[id].EN); });
  const ui=M["ui_main"]["LV"]; Object.assign(ui,{"title":"Sense Bridge","desc":"Oficiālās vēstules izskaidrotas jūsu valodā. Bez padomiem. Bez spiediena. Vienkārši skaidri.","paste":"Ielīmējiet vēstuli","photoTitle":"Vēstules foto","choosePhoto":"Izvēlēties foto","noPhoto":"Foto nav izvēlēts","readPhoto":"Nolasīt tekstu no foto","placeholder":"👇 Pieskarieties šeit un ielīmējiet vēstules vai e-pasta saturu…","btnAnalyze":"Analizēt vēstuli","userLang":"Jūsu valoda","sourceLangLabel":"Dokumenta valoda","fraudInfoTitle":"🛡️ Dokumenta drošības pārbaude","fraudInfoText":"Pēc analīzes Sense Bridge pārbaudīs arī iespējamu krāpšanas risku, uzdošanos par iestādi un aizdomīgus elementus dokumentā.","installApp":"📱 Pievienot Sense Bridge tālrunim","free":"BEZ MAKSAS:","analyses":"analīzes","access":"Piekļuve:","reset":"Testa atiestatīšana","lock":"Bezmaksas limits ir izmantots. Lai turpinātu, izvēlieties piekļuvi zemāk.","translation":"Tulkojums","summary":"Ko iestāde paziņo","risks":"Saziņas riski","examples":"Atbilžu piemēri","examplesUser":"Atbilžu piemēri (jūsu valodā)","examplesDoc":"Atbilžu piemēri (dokumenta valodā)","copyExDoc":"Kopēt atbildi nosūtīšanai","payTitle":"Piekļuve bez abonementa","payDesc":"Izmēģināšanai saņemat 3 BEZMAKSAS analīzes. Pēc tam izvēlieties piekļuves periodu.","p24meta":"Piekļuve analīzēm 24 stundas","p7meta":"Vairākiem ziņojumiem","p30meta":"Miers visam mēnesim","p7name":"7 dienas","p30name":"30 dienas","best":"Labākā vērtība","fine1":"Sense Bridge nesniedz juridiskas konsultācijas. Tas palīdz saprast nozīmi, toni un riskus, lai jūs varētu izlemt pats.","fine2":"Mēs piedāvājam mieru un sapratni, nevis „AI“.","hintUI":"„UI“ ir tikai lapas valoda (pogas un etiķetes); tā nemaina analīzi.","privacyNote":"<strong>Privātums:</strong> Dokumenti netiek publiski glabāti vai kopīgoti. Ielīmējiet tikai saturu, kuru vēlaties analizēt.","footerPrivacy":"Privātums","footerTerms":"Noteikumi","footerContact":"Kontakti","footerDefault":"Sense Bridge ir informatīvs rīks un nav juridiskais birojs.","analyzingLetter":"Vēstule tiek analizēta…","helpLinksTitle":"Noderīgas saites","srcAuto":"🌐 AUTO","clear":"Notīrīt datus pēc analīzes","copyTr":"Kopēt tulkojumu","copyEx":"Kopēt atbildes (manā valodā)"});
  Object.assign(M["m9112_SB_UX_COPY"]["LV"],{"main":"Katrs dokuments. Katra valoda.","sub":"Skaidrs skaidrojums, analīze un atbilde.","more":"Vairāk","moreTitle":"Vairāk opciju","install":"Instalēt lietotni","placeholder":"Ielīmējiet šeit vēstules vai e-pasta tekstu…"});
  Object.assign(M["m8484_COPY"]["LV"],{"label":"Lietotnes skats","sub":"Izvēlieties vienkāršu vai pilnu režīmu","simple":"Vienkāršs","full":"Pilns","language":"Jūsu lietotnes valoda","show":"📂 Rādīt pilnu analīzi","hide":"📁 Slēpt detaļas"});
  M["m8495_FLAGS"]["LV"]="🇱🇻 LV";
  M["m6857_langMap"]=M["m6857_langMap"]||Object.create(null); M["m6857_langMap"]["LV"]="LV";
  Object.assign(M["m9959_COPY"]["LV"],{"analysis":"Analīze","tools":"AI rīki","settings":"Iestatījumi"});
  Object.assign(M["m9695_COMMON"]["LV"],{"text":"📝 Ielīmēt tekstu","upload":"🖼️ Pievienot failu","take":"📷 Uzņemt foto","gallery":"🖼️ Izvēlēties no galerijas","pdf":"📄 Izvēlēties PDF","clear":"Notīrīt","close":"Aizvērt","none":"Fails nav izvēlēts.","empty":"Ielīmējiet tekstu vai pievienojiet failu.","extracting":"PDF tiek lasīts…","analyzing":"Analizē…","done":"Analīze ir gatava.","error":"Analīzi neizdevās pabeigt."});
  Object.assign(M["m4367_labels"]["LV"],{"light":"☀️ Gaišs","dark":"🌙 Tumšs"});
  Object.assign(M["m5186_map"]["LV"],{"takePhoto":"Uzņemt foto","chooseGallery":"Izvēlēties no galerijas","flow1Title":"1. Ko tas nozīmē?","flow1Text":"Vienkārši izskaidro dokumentu.","flow2Title":"2. Ko darīt tagad?","flow2Text":"Parāda nākamo soli.","flow3Title":"3. Vai tas ir droši?","flow3Text":"Pārbauda krāpšanas risku."});
  M["m5319_map"]["LV"]="Katrs dokuments. Katra valoda. Skaidrs skaidrojums, analīze un atbilde.";
  M["m5334_map"]["LV"]=["Saprotiet vēstuli","Ziniet, ko darīt tālāk","Pārbaudiet, vai tas izskatās droši","Gatavi atbilžu piemēri"];
  Object.assign(M["m5871_labels"]["LV"],{"flow":"ℹ️ Kā darbojas analīze?","info":"ℹ️ Informācija un privātums"});
  Object.assign(M["m6294_map"]["LV"],{"button":"📄 Jauna analīze","help":"Sāciet analizēt citu vēstuli.","toast":"✅ Gatavs! Varat analizēt citu vēstuli."});
  M["m8450_labels"]["LV"]="Sense Bridge novērtējums un soļi";
  Object.assign(M["m9206_SB_EXTRA_COPY"]["LV"],{"reach":"100+ valodas — saprotiet dokumentu savā valodā","takeScreenshot":"Uzņemt ekrāna foto","chooseScreenshot":"Izvēlēties no galerijas","noScreenshot":"Attēls nav izvēlēts"});
  Object.assign(M["m5491_map"]["LV"],{"title":"Jauni AI rīki","desc":"Izmēģiniet jebkuru jauno rīku 2 reizes. Pēc tam atbloķējiet Premium pakotni.","trials":"Izmēģinājuma lietojumi:","badge":"AI rīks","screenshotTitle":"Pārbaudīt ekrānuzņēmumu","screenshotDesc":"Ziņa, reklāma, brīdinājums vai aizdomīgs ekrāns.","linkTitle":"Pārbaudīt saiti vai vietni","linkDesc":"Domēna, uzdošanās un riska signālu pārbaude.","messageTitle":"Pārbaudīt e-pastu vai SMS","messageDesc":"Ziņa no uzņēmuma, iestādes, bankas vai nezināma sūtītāja.","replyTitle":"Atbildes asistents","replyDesc":"Pieklājīga, stingra vai neitrāla atbilde turpmākai rediģēšanai.","conversationTitle":"Sagatavoties sarunai","conversationDesc":"Jautājumi un frāzes sarunai ar iestādi vai uzņēmumu.","note":"Izvēlieties rīku, ievadiet saturu un izmantojiet vienu no 2 izmēģinājumiem.","locked":"Izmēģinājumi ir izmantoti. Atbloķējiet Premium pakotni."});
})(window);
