/* Sense Bridge V2 — NO. Safe Nordic extension: clone EN defaults, then override translated UI. */
(function(w){"use strict";
const R=(w.SB_I18N=w.SB_I18N||{modules:Object.create(null)}),M=R.modules;
function clone(v){if(Array.isArray(v))return v.map(clone);if(v&&typeof v==="object"){const o={};Object.keys(v).forEach(k=>o[k]=clone(v[k]));return o;}return v;}
Object.keys(M).forEach(id=>{if(M[id]&&M[id].EN!==undefined&&M[id]["NO"]===undefined)M[id]["NO"]=clone(M[id].EN);});
Object.assign(M["m4367_labels"]["NO"],{"light":"☀️ Lys","dark":"🌙 Mørk"});
Object.assign(M["m4500_map"]["NO"],{"title":"Tilgang","free":"FREE-analyser igjen","email":"E-post for tilgang","until":"Gyldig til","none":"Ikke tilkoblet","active":"Tilgang aktiv","freeMode":"FREE-modus","locked":"FREE-grensen er brukt","switchBtn":"Sjekk tilgang eller bruk en annen e-post","disconnect":"Koble fra e-post på denne enheten","note":"Å bytte eller koble fra e-postadressen sletter ikke kontoen eller servertilgangen.","emailTitle":"Skriv inn e-post for tilgang","emailText":"Skriv inn e-postadressen du vil bruke eller kontrollere.","notActive":"Ingen aktiv tilgang ble funnet for denne e-postadressen.","disconnected":"E-postadressen ble bare koblet fra på denne enheten.","disconnectTitle":"Koble fra e-post?","disconnectText":"Denne e-postadressen fjernes bare fra denne enheten. Kontoen og aktiv tilgang blir værende på serveren."});
Object.assign(M["m5186_map"]["NO"],{"takePhoto":"Ta et bilde","chooseGallery":"Velg fra galleri","flow1Title":"1. Hva betyr det?","flow1Text":"Forklarer dokumentet enkelt.","flow2Title":"2. Hva gjør jeg nå?","flow2Text":"Viser neste steg.","flow3Title":"3. Er det trygt?","flow3Text":"Sjekker risiko for svindel."});
M["m5319_map"]["NO"]="Hvert dokument. Hvert språk. Tydelig forklaring, analyse og svar.";
M["m5334_map"]["NO"]=["Forstå brevet","Vit hva du skal gjøre videre","Sjekk om det virker trygt","Ferdige svarforslag"];
Object.assign(M["m5464_packs"]["NO"],{"free":"GRATIS — igjen","basic":"BASIC — igjen","pro":"PRO — igjen"});
Object.assign(M["m5491_map"]["NO"],{"title":"Nye AI-verktøy","desc":"Prøv et valgfritt nytt verktøy 2 ganger. Lås deretter opp Premium-pakken.","trials":"Testbruk:","premium":"BASIC: 2 bruk • PRO: 100 bruk","badge":"AI-verktøy","screenshotTitle":"Sjekk et skjermbilde","screenshotDesc":"En melding, annonse, advarsel eller mistenkelig skjerm.","linkTitle":"Sjekk en lenke eller nettside","linkDesc":"Sjekk av domene, etterligning og risikosignaler.","messageTitle":"Sjekk e-post eller SMS","messageDesc":"En melding fra et firma, offentlig kontor, bank eller ukjent avsender.","replyTitle":"Svarassistent","replyDesc":"Et høflig, tydelig eller nøytralt svar for videre redigering.","conversationTitle":"Forbered en samtale","conversationDesc":"Spørsmål og setninger for kontor, firma eller institusjon.","note":"Velg et verktøy, legg inn innhold og bruk én av dine 2 tester.","used":"Testbruk registrert. Full funksjon kobles til i neste trinn.","locked":"Testene er brukt opp. Lås opp Premium."});
Object.assign(M["m5581_pack"]["NO"],{"useTrial":"Bruk test","close":"Lukk","empty":"Legg inn innhold for å kjøre en test."});
Object.assign(M["m5699_map"]["NO"],{"empty":"Legg inn innhold for å kjøre en test.","loading":"Analyserer…","what":"Hva det er","risk":"Risiko","next":"Hva du bør gjøre videre","reply":"Forslag","low":"Lav","medium":"Middels","high":"Høy"});
Object.assign(M["m5871_labels"]["NO"],{"flow":"ℹ️ Hvordan fungerer analysen?","info":"ℹ️ Informasjon og personvern"});
Object.assign(M["m6294_map"]["NO"],{"button":"📄 Ny analyse","help":"Start analysen av et nytt brev.","toast":"✅ Klar! Du kan analysere neste brev."});
Object.assign(M["m6479_dict"]["NO"],{"fraudRiskTitle":"Analyse av svindelrisiko","separatorText":"Sense Bridge-vurdering og trinn","fraudUnknown":"Ektheten kan ikke vurderes","fraudLow":"Virker ganske troverdig","fraudMedium":"Kontroller avsenderen","fraudHigh":"Høy svindelrisiko","fraudDisclaimer":"Dette er en risikoanalyse, ikke en bekreftelse på dokumentets ekthet.","confidence":"Sikkerhet","signals":"Signaler som bør sjekkes","suspicious":"Mistenkelige elementer","safeSteps":"Sikre trinn","country":"Land","officialWebsite":"Offisiell nettside","verifyInstitution":"Kontroller situasjonen via institusjonens offisielle nettside.","recognitionConfidence":"Gjenkjenningssikkerhet","legalNone":"Ingen juridisk hjelp er nødvendig","legalRecommended":"Det kan være nyttig å rådføre seg om situasjonen","legalUrgent":"Akutt juridisk hjelp kan være nødvendig","urgencyHigh":"HASTER – rask handling er nødvendig","urgencyMedium":"MIDDELS HASTER – det er verdt å svare","urgencyLow":"LAV HAST – du kan sjekke rolig","replyNeutral":"NØYTRAL","replyPolite":"HØFLIG","replyFirm":"TYDELIG","examplesDocFallback":"Svar på dokumentets språk kunne ikke lages automatisk. Velg dokumentets språk manuelt i stedet for AUTO og prøv igjen."});
M["m8450_labels"]["NO"]="Sense Bridge-vurdering og trinn";
Object.assign(M["m8484_COPY"]["NO"],{"label":"Appvisning","sub":"Velg enkel eller full opplevelse","simple":"Enkel","full":"Full","language":"Språket i appen","show":"📂 Vis full analyse","hide":"📁 Skjul detaljer"});
M["m8495_FLAGS"]["NO"]="🇳🇴 NO";
Object.assign(M["m8598_COPY"]["NO"],{"menu":"Meny","title":"Sense Bridge-meny","ai":"Nye AI-verktøy","aiSub":"Sjekk et skjermbilde, en lenke, en melding eller forbered et svar.","view":"Appvisning","viewSub":"Bytt mellom Enkel og Full visning.","benefits":"Hva appen gjør","benefitsSub":"Se de viktigste Sense Bridge-funksjonene.","access":"Tilgang","accessSub":"Sjekk FREE-analyser eller aktiv tilgang.","note":"I Full visning er alle seksjoner alltid synlige.","close":"Lukk"});
Object.assign(M["m9112_SB_UX_COPY"]["NO"],{"main":"Hvert dokument. Hvert språk.","sub":"Tydelig forklaring, analyse og svar.","more":"Mer","moreTitle":"Flere alternativer","install":"Installer appen","placeholder":"Lim inn teksten fra brevet eller e-posten her…"});
M["m9112_SB_UX_COPY"]["NO"].free=n=>`${n} gratis analyser igjen`;M["m9112_SB_UX_COPY"]["NO"].active=s=>`Tilgang aktiv: ${s}`;
Object.assign(M["m9206_SB_EXTRA_COPY"]["NO"],{"reach":"100+ språk — forstå dokumentet på ditt språk"});
Object.assign(M["m9695_COMMON"]["NO"],{"text":"📝 Lim inn tekst","upload":"🖼️ Legg til fil","take":"📷 Ta et bilde","gallery":"🖼️ Velg fra galleri","pdf":"📄 Velg PDF","clear":"Tøm","close":"Lukk","none":"Ingen fil valgt.","maxImages":"Du kan legge til maksimalt 5 bilder.","maxPdf":"En PDF kan inneholde maksimalt 10 sider i denne testversjonen.","empty":"Lim inn tekst eller legg til en fil.","extracting":"Leser PDF…","analyzing":"Analyserer…","done":"Analysen er klar.","error":"Analysen kunne ikke fullføres.","locked":"De gratis AI-testene er brukt. Aktiver Premium.","pdfLoad":"PDF-leseren kunne ikke startes. Kontroller internettforbindelsen."});
Object.assign(M["m9959_COPY"]["NO"],{"analysis":"Analyse","tools":"AI-verktøy","settings":"Innstillinger"});
Object.assign(M["ui_main"]["NO"],{"title":"Sense Bridge","desc":"Offisielle brev forklart på ditt språk. Ingen råd. Ikke noe press. Bare tydelighet.","paste":"Lim inn brevet","photoTitle":"Bilde av brevet","choosePhoto":"Velg bilde","noPhoto":"Ingen bilde valgt","readPhoto":"Les tekst fra bilde","placeholder":"👇 Trykk her og lim inn innholdet i brevet eller e-posten…","btnAnalyze":"Analyser brevet","userLang":"Ditt språk","sourceLangLabel":"Dokumentets språk","installApp":"📱 Legg Sense Bridge til på telefonen","fraudInfoTitle":"🛡️ Sikkerhetssjekk av dokument","translation":"Oversettelse","summary":"Hva myndigheten formidler","risks":"Kommunikasjonsrisiko","examples":"Svarforslag","free":"FREE:","analyses":"analyser","access":"Tilgang:","srcAuto":"🌐 AUTO","clear":"Tøm","copyTr":"Kopier oversettelse","footerPrivacy":"Personvern","footerTerms":"Vilkår","footerContact":"Kontakt","analyzingLetter":"Analyserer brevet…"});
M["m6857_langMap"]=M["m6857_langMap"]||Object.create(null);M["m6857_langMap"]["NO"]="NO";

/* Nordic completeness patch — UI text only. */
Object.assign(M["m7463_SB_UX_V10_TEXT"]["NO"],{progressTitle:"Dokumentanalyse",progress1:"Forbereder",progress2:"Leser tekst",progress3:"Innholdsanalyse",progress4:"Sikkerhetssjekk",progress5:"Ferdig",statusPreparing:"Forbereder analyse...",statusReading:"Leser dokumentet...",statusAnalyzing:"Analyserer innholdet...",statusSafety:"Kontrollerer sikkerheten...",statusDone:"Ferdig – se nedenfor",statusError:"Analysefeil",quickTitle:"✨ Kort sammendrag",quickMeaning:"📝 Hva betyr dette?",quickAction:"⚠️ Må jeg gjøre noe?",quickSafety:"🛡️ Er det trygt?",noShortSummary:"Ingen kort oppsummering er tilgjengelig. Se detaljene nedenfor.",noAction:"Ingen tydelig handling ble funnet. Sjekk analysedetaljene.",lowUrgency:"Lav hast",mediumUrgency:"Middels hast",highUrgency:"Haster",unknownUrgency:"Ikke angitt",safeLow:"Virker ganske trygt",safeMedium:"Verdt å kontrollere",safeHigh:"Høy risiko",safeUnknown:"Kan ikke vurderes",printPdf:"📄 Last ned / lagre PDF",printHint:"Bruk telefonens utskriftsfunksjon for å lagre resultatet som PDF."});
Object.assign(M["m9206_SB_EXTRA_COPY"]["NO"],{takeScreenshot:"Ta et bilde av skjermen",chooseScreenshot:"Velg fra galleri",noScreenshot:"Ingen bilde valgt"});
Object.assign(M["ui_main"]["NO"],{fraudInfoText:"Etter analysen kontrollerer Sense Bridge også mulig svindelrisiko, etterligning av en institusjon og mistenkelige elementer i dokumentet.",installHelp:"Legg til en app-snarvei på telefonen:\\n\\nTrykk på de tre prikkene i nettleseren\\n→ Legg til på startskjermen",free:"GRATIS:",reset:"Tilbakestill test",lock:"Gratisgrensen din er brukt. Velg tilgang nedenfor for å fortsette.",examplesUser:"Svarforslag (ditt språk)",examplesDoc:"Svarforslag (dokumentets språk)",copyExDoc:"Kopier svar for sending",examplesDocEmpty:"Etter analysen vises svaret på dokumentets språk her.",payTitle:"Tilgang uten abonnement",payDesc:"Du får først 3 gratis analyser å prøve. Velg deretter en passende tilgangsperiode.",p24meta:"Tilgang til analyser i 24 timer",p7meta:"For en serie meldinger",p30meta:"Ro i en hel måned",p7name:"7 dager",p30name:"30 dager",best:"Beste verdi",fine1:"Sense Bridge gir ikke juridisk rådgivning. Det hjelper deg å forstå betydning, tone og risiko slik at du kan bestemme selv.",fine2:"Vi tilbyr klarhet og ro, ikke bare ‘AI’.",hintUI:"‘UI’ er bare språket på siden (knapper og etiketter) – det endrer ikke analysen.",privacyNote:"<strong>Personvern:</strong> Dokumenter lagres ikke offentlig og deles ikke. Lim bare inn innhold du vil analysere.",footerDefault:"Sense Bridge er en informasjonstjeneste og er ikke et advokatfirma.",footerPrivacyText:"Personvern: vi publiserer ikke brukernes dokumenter. Tekniske data og tilgangsinformasjon brukes bare for å drive tjenesten.",footerTermsText:"Vilkår: brukeren er ansvarlig for innholdet som limes inn. Analysen er informativ og er ikke juridisk rådgivning.",footerContactText:"Kontakt: ved tilgangs- eller betalingsproblemer, bruk kontaktadressen som Sense Bridge oppgir.",helpLinksTitle:"Nyttige lenker",copyEx:"Kopier svar (mitt språk)"});
Object.assign(M["m6113_t"]["NO"],{lead:"Bruk Sense Bridge som en vanlig app.",hint:"Trykk på menyen med tre prikker i nettleseren og velg ‘Legg til på startskjermen’."});
Object.assign(M["m6138_map"]["NO"],{title:"Kjøp tilgang",amount:"Beløp:",transfer:"Betal med bankoverføring:",receiver:"Mottaker:",transferTitle:"Betalingsreferanse:",paid:"✔ Jeg har betalt",saved:"✅ Forespørsel lagret",savedText:"Takk. Utfør bankoverføringen med nøyaktig betalingsreferansen nedenfor. Tilgangen aktiveres etter manuell betalingsbekreftelse.",copy:"Kopier betalingsreferanse",small:"Når betalingen er mottatt, aktiverer vi tilgangen. Du kan senere komme tilbake og sjekke tilgangen med samme e-postadresse."});
Object.assign(M["m7072_txt"]["NO"],{emailTitle:"Skriv inn e-postadressen din",emailText:"Vi knytter betalingsforespørselen og tilgangen til denne adressen.",copied:"Kopiert ✔",copiedText:"Betalingsreferansen er kopiert.",noEmail:"Skriv inn e-postadressen først.",noPlan:"Ingen plan er valgt.",blocked:"Denne e-postadressen er blokkert.",error:"Feil: ",activationError:"Aktiveringsfeil",pendingTitle:"Forespørsel lagret ✔",pendingText:"Utfør overføringen med oppgitt referanse. Tilgangen aktiveres etter betalingsbekreftelse."});
Object.assign(M["m6799_dict"]["NO"],{recognizedInstitution:"Gjenkjent institusjon",countryFromDocument:"Land fra dokumentet",probableCountry:"Sannsynlig landskontekst",countryNotCertain:"Institusjonens land ble ikke tydelig bekreftet i dokumentteksten.",basedOnContent:"basert på dokumenttekst/lenker",basedOnLanguage:"basert på dokumentets språk – bare et hint",websiteHidden:"Ingen nasjonal nettside vises som sikker fordi landet ikke er godt nok bekreftet.",safeInstitutionStep:"Ikke klikk på lenker i meldingen. Åpne den offisielle appen eller søk etter institusjonen selv.",officialWebsiteShown:"Nettsiden vises bare når den ikke strider mot dokumentets kontekst."});
Object.assign(M["m7375_dict"]["NO"],{HIGH:"🚨 Høy svindelrisiko. Ikke klikk på lenker; kontroller via en offisiell kanal.",MEDIUM:"⚠️ Dokumentet må kontrolleres nøye. Sjekk avsender, lenker og frist via det offisielle nettstedet.",LOW:"✅ Ingen sterke svindelsignaler ble funnet. Kontroller likevel detaljene i dokumentet.",UNKNOWN:"ℹ️ Dokumentets sikkerhet kan ikke vurderes tydelig. Kontroller avsenderen via en offisiell kanal."});
Object.assign(M["m6039_map"]["NO"],{name:"30 dager PRO",meta:"Full tilgang + avanserte AI-verktøy",features:"100 bruk av AI-verktøy i 30 dager pluss full tilgang til standardanalyse.",aria:"Velg 30 dagers PRO-tilgang for 25 euro"});
Object.assign(M["m5581_pack"]["NO"].previewDesc,{screenshot:"Beskriv den mistenkelige skjermen, meldingen, annonsen eller advarselen.",link:"Lim inn lenken eller nettadressen du vil kontrollere.",message:"Lim inn innholdet i e-posten, SMS-en eller meldingen.",reply:"Lim inn meldingen eller brevet du vil svare på.",conversation:"Beskriv hvem du skal snakke med og hva saken gjelder."});
Object.assign(M["m5581_pack"]["NO"].placeholder,{screenshot:"Eksempel: virusvarsel, betalingskrav, popup-annonse...",link:"Lim inn lenken her, f.eks. https://...",message:"Lim inn meldingsinnholdet...",reply:"Lim inn brevet eller meldingsinnholdet...",conversation:"Eksempel: samtale med offentlig kontor, bank, arbeidsgiver eller skole..."});


Object.assign(M["m9439_COPY"]["NO"],{tool:"Kontraktsanalyse",toolDesc:"Viktige klausuler, plikter, frister og punkter som krever oppmerksomhet.",title:"Kontraktsanalyse",desc:"Lim inn kontraktsteksten eller legg til opptil 5 bilder av sammenhengende sider.",textTab:"📝 Lim inn tekst",imagesTab:"🖼️ Legg til bilder",placeholder:"Lim inn kontraktsteksten her...",camera:"📷 Ta et bilde",gallery:"🖼️ Velg fra galleri",note:"Sense Bridge fremhever viktige klausuler og mulige risikoer. Dette er informativ AI-veiledning, ikke juridisk rådgivning.",run:"Analyser kontrakt",clear:"Tøm",close:"Lukk",empty:"Lim inn kontraktsteksten eller legg til minst ett bilde.",tooMany:"Du kan legge til maksimalt 5 bilder.",analyzing:"Analyserer kontrakt...",done:"Kontraktsanalysen er klar.",error:"Kontrakten kunne ikke analyseres.",locked:"De gratis AI-testene er brukt. Aktiver Premium.",overview:"📋 Hva slags kontrakt dette er og hva den gjelder",duties:"✅ Plikter og viktige vilkår",dates:"📅 Frister, oppsigelse og fornyelse",risks:"⚠️ Klausuler som krever oppmerksomhet",next:"➡️ Hva du bør kontrollere eller gjøre videre",plain:"🌍 Enkel forklaring / oversettelse"});
Object.assign(M["m9707_TOOLS"]["NO"],{pdf:{title:"PDF-analyse",desc:"Legg til et PDF-dokument på opptil 10 sider. Sense Bridge trekker ut tekst og sender skannede sider til OCR.",card:"Les og forklar et flersidig PDF-dokument.",run:"Analyser PDF",placeholder:"Du kan også lime inn tekst fra et PDF-dokument...",note:"Testversjon: maks 10 sider. Dokumenter lagres ikke.",labels:["📋 Hva dokumentet er","🏛️ Utsteder og formål","📅 Frister og datoer","⚠️ Viktige eller uklare punkter","➡️ Hva du skal gjøre videre","🌍 Enkel forklaring"]},form:{title:"Skjemahjelp",desc:"Lim inn et skjema eller legg til opptil 5 bilder av sammenhengende sider.",card:"Forklaring av felt, nødvendig informasjon og dokumenter.",run:"Forklar skjema",placeholder:"Lim inn skjemateksten eller beskriv hva du trenger hjelp med...",note:"Sense Bridge forklarer feltene, men fyller ikke inn opplysningene dine og sender ikke skjemaet.",labels:["📋 Skjemaets formål","📝 Hvordan feltene fylles ut","📎 Nødvendig informasjon og dokumenter","⚠️ Felt som krever oppmerksomhet","➡️ Neste trinn","🌍 Enkel forklaring"]},photo:{title:"Bildeanalyse",desc:"Legg til opptil 5 bilder med tekst, varsel, skilt eller dokument.",card:"Les og forklar tekst som er synlig i bilder.",run:"Analyser bilder",placeholder:"Beskriv eventuelt bildet eller hva du vil vite...",note:"Bildet bør være skarpt, godt belyst og inneholde all tekst.",labels:["🖼️ Hva bildene viser","📄 Uthentet innhold","🏛️ Avsender eller kilde","⚠️ Viktige signaler","➡️ Hva du skal gjøre videre","🌍 Enkel forklaring / oversettelse"]},bill:{title:"Regninger og fakturaer",desc:"Lim inn fakturatekst eller legg til opptil 5 bilder av sidene.",card:"Beløp, betalingsfrister, linjer og mulige uklare gebyrer.",run:"Forklar regning",placeholder:"Lim inn regningen eller fakturateksten...",note:"Sense Bridge gir informativ veiledning. Kontroller mottaker og bankopplysninger før betaling.",labels:["🧾 Hva regningen gjelder","💶 Beløp og linjer","📅 Betalingsfrist og metode","⚠️ Gebyrer eller uklare punkter","➡️ Hva du bør kontrollere før betaling","🌍 Enkel forklaring"]}});

Object.assign(M["m5723_copy"]["NO"],{screenshot:{what:"Dette ser ut som en skjerm eller advarsel som bør kontrolleres.",next:"Ikke trykk på knapper eller lenker før du har kontrollert kilden. Sammenlign med det offisielle nettstedet.",reply:"Hvis det hevdes å komme fra en institusjon, åpne det offisielle nettstedet selv."},link:{what:"Dette er en lenke eller nettadresse som bør kontrolleres.",next:"Kontroller domenet selv. Ikke logg inn via en lenke i en melding. Åpne det offisielle nettstedet selv.",reply:"Det er tryggere å åpne det offisielle nettstedet via søk eller et lagret bokmerke."},message:{what:"Dette ser ut som en melding som bør kontrolleres for phishing eller press.",next:"Kontroller avsenderen, domenet og om meldingen presser deg til rask handling. Ikke del innloggingsopplysninger.",reply:"Takk for meldingen. Jeg vil kontrollere dette via den offisielle kontaktkanalen."},reply:{what:"Dette er en situasjon der et rolig svar kan forberedes.",next:"Svar kort og tydelig uten unødvendige personopplysninger.",reply:"Takk for meldingen. Vennligst forklar saken og hvilken handling som kreves av meg."},conversation:{what:"Dette er et tema for en samtale som det er lurt å forberede.",next:"Skriv ned målet, dokumentene du skal ta med og 2–3 spørsmål.",reply:"Jeg vil gjerne avklare dette rolig. Fortell meg de neste trinnene og hvilke dokumenter som trengs."}});

})(window);

// Nordic install dialog
window.SB_INSTALL_I18N = window.SB_INSTALL_I18N || {};
window.SB_INSTALL_I18N.NO = {
  title: "Legg til Sense Bridge<br>på telefonen din",
  text: "Ha alltid Sense Bridge lett tilgjengelig.",
  privacy: "Brevene og bildene dine lagres eller deles ikke.",
  step: "Trykk på nettleserens meny med <b>tre prikker</b> og velg:",
  add: "Legg til på startskjermen",
  ok: "Skjønner"
};

/* Nordic full-message audit patch v4 — function-valued UI strings only. */
(function(w){"use strict";const M=w.SB_I18N&&w.SB_I18N.modules;if(!M)return;
if(M["m9439_COPY"]&&M["m9439_COPY"].NO){M["m9439_COPY"].NO.count=n=>`Valgt: ${n}/5`;M["m9439_COPY"].NO.reading=(i,n)=>`Leser side ${i} av ${n}...`;}
if(M["m9695_COMMON"]&&M["m9695_COMMON"].NO){M["m9695_COMMON"].NO.selected=n=>`Valgt: ${n}/5`;M["m9695_COMMON"].NO.reading=(i,n)=>`Leser side ${i} av ${n}...`;}
})(window);
