/* Sense Bridge V2 — SV. Safe Nordic extension: clone EN defaults, then override translated UI. */
(function(w){"use strict";
const R=(w.SB_I18N=w.SB_I18N||{modules:Object.create(null)}),M=R.modules;
function clone(v){if(Array.isArray(v))return v.map(clone);if(v&&typeof v==="object"){const o={};Object.keys(v).forEach(k=>o[k]=clone(v[k]));return o;}return v;}
Object.keys(M).forEach(id=>{if(M[id]&&M[id].EN!==undefined&&M[id]["SV"]===undefined)M[id]["SV"]=clone(M[id].EN);});
Object.assign(M["m4367_labels"]["SV"],{"light":"☀️ Ljust","dark":"🌙 Mörkt"});
Object.assign(M["m4500_map"]["SV"],{"title":"Åtkomst","free":"FREE-analyser kvar","email":"E-post för åtkomst","until":"Giltig till","none":"Inte ansluten","active":"Åtkomst aktiv","freeMode":"FREE-läge","locked":"FREE-gränsen är använd","switchBtn":"Kontrollera åtkomst eller använd en annan e-post","disconnect":"Koppla bort e-post på den här enheten","note":"Att byta eller koppla bort e-postadressen tar inte bort kontot eller serveråtkomsten.","emailTitle":"Ange e-post för åtkomst","emailText":"Ange e-postadressen du vill använda eller kontrollera.","notActive":"Ingen aktiv åtkomst hittades för den här e-postadressen.","disconnected":"E-postadressen kopplades bara bort på den här enheten.","disconnectTitle":"Koppla bort e-post?","disconnectText":"Den här e-postadressen tas bara bort från den här enheten. Kontot och den aktiva åtkomsten finns kvar på servern."});
Object.assign(M["m5186_map"]["SV"],{"takePhoto":"Ta ett foto","chooseGallery":"Välj från galleri","flow1Title":"1. Vad betyder det?","flow1Text":"Förklarar dokumentet enkelt.","flow2Title":"2. Vad gör jag nu?","flow2Text":"Visar nästa steg.","flow3Title":"3. Är det säkert?","flow3Text":"Kontrollerar risken för bedrägeri."});
M["m5319_map"]["SV"]="Varje dokument. Varje språk. Tydlig förklaring, analys och svar.";
M["m5334_map"]["SV"]=["Förstå brevet","Vet vad du ska göra härnäst","Kontrollera om det verkar säkert","Färdiga svarsexempel"];
Object.assign(M["m5464_packs"]["SV"],{"free":"GRATIS — kvar","basic":"BASIC — kvar","pro":"PRO — kvar"});
Object.assign(M["m5491_map"]["SV"],{"title":"Nya AI-verktyg","desc":"Prova valfritt nytt verktyg 2 gånger. Lås sedan upp Premium-paketet.","trials":"Testanvändningar:","premium":"BASIC: 2 användningar • PRO: 100 användningar","badge":"AI-verktyg","screenshotTitle":"Kontrollera en skärmbild","screenshotDesc":"Ett meddelande, en annons, varning eller misstänkt skärm.","linkTitle":"Kontrollera en länk eller webbplats","linkDesc":"Kontroll av domän, imitation och risksignaler.","messageTitle":"Kontrollera e-post eller SMS","messageDesc":"Ett meddelande från företag, myndighet, bank eller okänd avsändare.","replyTitle":"Svarshjälp","replyDesc":"Ett artigt, bestämt eller neutralt svar för vidare redigering.","conversationTitle":"Förbered ett samtal","conversationDesc":"Frågor och fraser för myndighet, företag eller institution.","note":"Välj ett verktyg, ange innehåll och använd ett av dina 2 test.","used":"Testanvändningen är markerad. Full funktion ansluts i nästa steg.","locked":"Testanvändningarna är slut. Lås upp Premium."});
Object.assign(M["m5581_pack"]["SV"],{"useTrial":"Använd test","close":"Stäng","empty":"Ange innehåll för att köra ett test."});
Object.assign(M["m5699_map"]["SV"],{"empty":"Ange innehåll för att köra ett test.","loading":"Analyserar…","what":"Vad det är","risk":"Risk","next":"Vad du ska göra härnäst","reply":"Förslag","low":"Låg","medium":"Medel","high":"Hög"});
Object.assign(M["m5871_labels"]["SV"],{"flow":"ℹ️ Hur fungerar analysen?","info":"ℹ️ Information och integritet"});
Object.assign(M["m6294_map"]["SV"],{"button":"📄 Ny analys","help":"Börja analysera ett annat brev.","toast":"✅ Klar! Du kan analysera nästa brev."});
Object.assign(M["m6479_dict"]["SV"],{"fraudRiskTitle":"Analys av bedrägeririsk","separatorText":"Sense Bridge-bedömning och steg","fraudUnknown":"Äktheten kan inte bedömas","fraudLow":"Verkar ganska trovärdigt","fraudMedium":"Verifiera avsändaren","fraudHigh":"Hög risk för bedrägeri","fraudDisclaimer":"Detta är en riskanalys, inte en bekräftelse på dokumentets äkthet.","confidence":"Säkerhet","signals":"Signaler att kontrollera","suspicious":"Misstänkta delar","safeSteps":"Säkra steg","country":"Land","officialWebsite":"Officiell webbplats","verifyInstitution":"Verifiera situationen via institutionens officiella webbplats.","recognitionConfidence":"Igenkänningssäkerhet","legalNone":"Ingen juridisk hjälp behövs","legalRecommended":"Det kan vara värt att rådgöra om situationen","legalUrgent":"Brådskande juridisk hjälp kan behövas","urgencyHigh":"BRÅDSKANDE – snabb åtgärd krävs","urgencyMedium":"MEDELHÖG BRÅDSKA – det är värt att svara","urgencyLow":"LÅG BRÅDSKA – du kan kontrollera i lugn och ro","replyNeutral":"NEUTRAL","replyPolite":"ARTIG","replyFirm":"BESTÄMD","examplesDocFallback":"Svaret på dokumentets språk kunde inte skapas automatiskt. Välj dokumentets språk manuellt i stället för AUTO och försök igen."});
M["m8450_labels"]["SV"]="Sense Bridge-bedömning och steg";
Object.assign(M["m8484_COPY"]["SV"],{"label":"Appvy","sub":"Välj en enkel eller fullständig upplevelse","simple":"Enkel","full":"Full","language":"Ditt appspråk","show":"📂 Visa full analys","hide":"📁 Dölj detaljer"});
M["m8495_FLAGS"]["SV"]="🇸🇪 SV";
Object.assign(M["m8598_COPY"]["SV"],{"menu":"Meny","title":"Sense Bridge-meny","ai":"Nya AI-verktyg","aiSub":"Kontrollera en skärmbild, länk, ett meddelande eller förbered ett svar.","view":"Appvy","viewSub":"Växla mellan Enkel och Full vy.","benefits":"Vad appen gör","benefitsSub":"Se de viktigaste Sense Bridge-funktionerna.","access":"Åtkomst","accessSub":"Kontrollera FREE-analyser eller aktiv åtkomst.","note":"I Full vy är alla sektioner alltid synliga.","close":"Stäng"});
Object.assign(M["m9112_SB_UX_COPY"]["SV"],{"main":"Varje dokument. Varje språk.","sub":"Tydlig förklaring, analys och svar.","more":"Mer","moreTitle":"Fler alternativ","install":"Installera appen","placeholder":"Klistra in texten från brevet eller e-postmeddelandet här…"});
M["m9112_SB_UX_COPY"]["SV"].free=n=>`${n} gratis analyser kvar`;M["m9112_SB_UX_COPY"]["SV"].active=s=>`Åtkomst aktiv: ${s}`;
Object.assign(M["m9206_SB_EXTRA_COPY"]["SV"],{"reach":"100+ språk — förstå dokumentet på ditt språk"});
Object.assign(M["m9695_COMMON"]["SV"],{"text":"📝 Klistra in text","upload":"🖼️ Lägg till fil","take":"📷 Ta ett foto","gallery":"🖼️ Välj från galleri","pdf":"📄 Välj PDF","clear":"Rensa","close":"Stäng","none":"Ingen fil vald.","maxImages":"Du kan lägga till högst 5 foton.","maxPdf":"En PDF kan innehålla högst 10 sidor i den här testversionen.","empty":"Klistra in text eller lägg till en fil.","extracting":"Läser PDF…","analyzing":"Analyserar…","done":"Analysen är klar.","error":"Analysen kunde inte slutföras.","locked":"De kostnadsfria AI-testerna är använda. Aktivera Premium.","pdfLoad":"PDF-läsaren kunde inte startas. Kontrollera internetanslutningen."});
Object.assign(M["m9959_COPY"]["SV"],{"analysis":"Analys","tools":"AI-verktyg","settings":"Inställningar"});
Object.assign(M["ui_main"]["SV"],{"title":"Sense Bridge","desc":"Officiella brev förklarade på ditt språk. Inga råd. Ingen press. Bara tydlighet.","paste":"Klistra in brevet","photoTitle":"Foto av brevet","choosePhoto":"Välj foto","noPhoto":"Inget foto valt","readPhoto":"Läs text från foto","placeholder":"👇 Tryck här och klistra in innehållet i brevet eller e-postmeddelandet…","btnAnalyze":"Analysera brevet","userLang":"Ditt språk","sourceLangLabel":"Dokumentets språk","installApp":"📱 Lägg till Sense Bridge på din telefon","fraudInfoTitle":"🛡️ Säkerhetskontroll av dokument","translation":"Översättning","summary":"Vad myndigheten meddelar","risks":"Kommunikationsrisker","examples":"Svarsexempel","free":"FREE:","analyses":"analyser","access":"Åtkomst:","srcAuto":"🌐 AUTO","clear":"Rensa","copyTr":"Kopiera översättning","footerPrivacy":"Integritet","footerTerms":"Villkor","footerContact":"Kontakt","analyzingLetter":"Analyserar brevet…"});
M["m6857_langMap"]=M["m6857_langMap"]||Object.create(null);M["m6857_langMap"]["SV"]="SE";

/* Nordic completeness patch — UI text only. */
Object.assign(M["m7463_SB_UX_V10_TEXT"]["SV"],{progressTitle:"Dokumentanalys",progress1:"Förbereder",progress2:"Läser text",progress3:"Innehållsanalys",progress4:"Säkerhetskontroll",progress5:"Klart",statusPreparing:"Förbereder analys...",statusReading:"Läser dokumentet...",statusAnalyzing:"Analyserar innehållet...",statusSafety:"Kontrollerar säkerheten...",statusDone:"Klart – se nedan",statusError:"Analysfel",quickTitle:"✨ Kort sammanfattning",quickMeaning:"📝 Vad betyder det?",quickAction:"⚠️ Behöver jag göra något?",quickSafety:"🛡️ Är det säkert?",noShortSummary:"Ingen kort sammanfattning finns. Se detaljerna nedan.",noAction:"Ingen tydlig åtgärd hittades. Kontrollera analysdetaljerna.",lowUrgency:"Låg brådska",mediumUrgency:"Medelhög brådska",highUrgency:"Brådskande",unknownUrgency:"Inte angivet",safeLow:"Verkar ganska säkert",safeMedium:"Värt att kontrollera",safeHigh:"Hög risk",safeUnknown:"Kan inte bedömas",printPdf:"📄 Ladda ner / spara PDF",printHint:"Använd telefonens utskriftsfunktion för att spara resultatet som PDF."});
Object.assign(M["m9206_SB_EXTRA_COPY"]["SV"],{takeScreenshot:"Ta ett foto av skärmen",chooseScreenshot:"Välj från galleri",noScreenshot:"Ingen bild vald"});
Object.assign(M["ui_main"]["SV"],{fraudInfoText:"Efter analysen kontrollerar Sense Bridge även möjlig bedrägeririsk, imitation av en institution och misstänkta delar i dokumentet.",installHelp:"Lägg till en appgenväg på telefonen:\\n\\nTryck på webbläsarens tre punkter\\n→ Lägg till på startskärmen",free:"GRATIS:",reset:"Återställ test",lock:"Din gratisgräns är använd. Välj åtkomst nedan för att fortsätta.",examplesUser:"Svarsexempel (ditt språk)",examplesDoc:"Svarsexempel (dokumentets språk)",copyExDoc:"Kopiera svar att skicka",examplesDocEmpty:"Efter analysen visas svaret på dokumentets språk här.",payTitle:"Åtkomst utan abonnemang",payDesc:"Du får först 3 gratis analyser att prova. Välj sedan en passande åtkomstperiod.",p24meta:"Tillgång till analyser i 24 timmar",p7meta:"För en serie meddelanden",p30meta:"Lugn i en hel månad",p7name:"7 dagar",p30name:"30 dagar",best:"Bästa värde",fine1:"Sense Bridge ger inte juridisk rådgivning. Det hjälper dig förstå betydelse, ton och risker så att du kan fatta beslut själv.",fine2:"Vi erbjuder tydlighet och lugn, inte bara ‘AI’.",hintUI:"‘UI’ är bara sidans språk (knappar och etiketter) – det ändrar inte analysen.",privacyNote:"<strong>Integritet:</strong> Dokument lagras inte offentligt och delas inte. Klistra bara in innehåll du vill analysera.",footerDefault:"Sense Bridge är en informationstjänst och är inte en advokatbyrå.",footerPrivacyText:"Integritet: vi publicerar inte användarnas dokument. Tekniska data och åtkomstinformation används endast för att driva tjänsten.",footerTermsText:"Villkor: användaren ansvarar för innehållet som klistras in. Analysen är informativ och är inte juridisk rådgivning.",footerContactText:"Kontakt: vid åtkomst- eller betalningsproblem, använd kontaktadressen som Sense Bridge anger.",helpLinksTitle:"Användbara länkar",copyEx:"Kopiera svar (mitt språk)"});
Object.assign(M["m6113_t"]["SV"],{lead:"Använd Sense Bridge som en vanlig app.",hint:"Tryck på webbläsarens meny med tre punkter och välj ‘Lägg till på startskärmen’."});
Object.assign(M["m6138_map"]["SV"],{title:"Köp åtkomst",amount:"Belopp:",transfer:"Betala via banköverföring:",receiver:"Mottagare:",transferTitle:"Betalningsreferens:",paid:"✔ Jag har betalat",saved:"✅ Begäran sparad",savedText:"Tack. Gör banköverföringen med exakt betalningsreferensen nedan. Åtkomsten aktiveras efter manuell betalningsbekräftelse.",copy:"Kopiera betalningsreferens",small:"När betalningen har mottagits aktiverar vi åtkomsten. Du kan senare återvända och kontrollera åtkomsten med samma e-postadress."});
Object.assign(M["m7072_txt"]["SV"],{emailTitle:"Ange din e-postadress",emailText:"Vi kopplar betalningsbegäran och åtkomsten till den här adressen.",copied:"Kopierat ✔",copiedText:"Betalningsreferensen har kopierats.",noEmail:"Ange din e-postadress först.",noPlan:"Ingen plan är vald.",blocked:"Den här e-postadressen är blockerad.",error:"Fel: ",activationError:"Aktiveringsfel",pendingTitle:"Begäran sparad ✔",pendingText:"Gör överföringen med den angivna referensen. Åtkomsten aktiveras efter betalningsbekräftelse."});
Object.assign(M["m6799_dict"]["SV"],{recognizedInstitution:"Identifierad institution",countryFromDocument:"Land enligt dokumentet",probableCountry:"Trolig landskontext",countryNotCertain:"Institutionens land kunde inte bekräftas tydligt i dokumenttexten.",basedOnContent:"baserat på dokumenttext/länkar",basedOnLanguage:"baserat på dokumentets språk – endast en ledtråd",websiteHidden:"Ingen nationell webbplats visas som säker eftersom landet inte är tillräckligt bekräftat.",safeInstitutionStep:"Klicka inte på länkar i meddelandet. Öppna den officiella appen eller sök efter institutionen själv.",officialWebsiteShown:"Webbplatsen visas endast när den inte strider mot dokumentets sammanhang."});
Object.assign(M["m7375_dict"]["SV"],{HIGH:"🚨 Hög bedrägeririsk. Klicka inte på länkar; kontrollera via en officiell kanal.",MEDIUM:"⚠️ Dokumentet behöver kontrolleras noggrant. Kontrollera avsändare, länkar och tidsfrist via den officiella webbplatsen.",LOW:"✅ Inga starka bedrägerisignaler hittades. Kontrollera ändå dokumentets uppgifter.",UNKNOWN:"ℹ️ Dokumentets säkerhet kan inte bedömas tydligt. Kontrollera avsändaren via en officiell kanal."});
Object.assign(M["m6039_map"]["SV"],{name:"30 dagar PRO",meta:"Full åtkomst + avancerade AI-verktyg",features:"100 användningar av AI-verktyg i 30 dagar plus full åtkomst till standardanalys.",aria:"Välj 30 dagars PRO-åtkomst för 25 euro"});
Object.assign(M["m5581_pack"]["SV"].previewDesc,{screenshot:"Beskriv den misstänkta skärmen, meddelandet, annonsen eller varningen.",link:"Klistra in länken eller webbplatsadressen du vill kontrollera.",message:"Klistra in innehållet i e-postmeddelandet, SMS:et eller meddelandet.",reply:"Klistra in meddelandet eller brevet du vill svara på.",conversation:"Beskriv vem du ska prata med och vad ärendet gäller."});
Object.assign(M["m5581_pack"]["SV"].placeholder,{screenshot:"Exempel: virusvarning, betalningsbegäran, popup-annons...",link:"Klistra in länken här, t.ex. https://...",message:"Klistra in meddelandets innehåll...",reply:"Klistra in brevet eller meddelandets innehåll...",conversation:"Exempel: samtal med myndighet, bank, arbetsgivare eller skola..."});
Object.assign(M["m5699_map"]["SV"],{risk:"Risk"});
Object.assign(M["m6479_dict"]["SV"],{replyNeutral:"NEUTRAL"});


Object.assign(M["m9439_COPY"]["SV"],{tool:"Avtalsanalys",toolDesc:"Viktiga klausuler, skyldigheter, tidsfrister och punkter som kräver uppmärksamhet.",title:"Avtalsanalys",desc:"Klistra in avtalstexten eller lägg till upp till 5 foton av sidor i följd.",textTab:"📝 Klistra in text",imagesTab:"🖼️ Lägg till foton",placeholder:"Klistra in avtalstexten här...",camera:"📷 Ta ett foto",gallery:"🖼️ Välj från galleri",note:"Sense Bridge markerar viktiga klausuler och möjliga risker. Detta är informativ AI-vägledning, inte juridisk rådgivning.",run:"Analysera avtal",clear:"Rensa",close:"Stäng",empty:"Klistra in avtalstexten eller lägg till minst ett foto.",tooMany:"Du kan lägga till högst 5 foton.",analyzing:"Analyserar avtal...",done:"Avtalsanalysen är klar.",error:"Avtalet kunde inte analyseras.",locked:"De kostnadsfria AI-försöken är använda. Aktivera Premium.",overview:"📋 Vilken typ av avtal det är och vad det omfattar",duties:"✅ Skyldigheter och viktiga villkor",dates:"📅 Tidsfrister, uppsägning och förnyelse",risks:"⚠️ Klausuler som kräver uppmärksamhet",next:"➡️ Vad du bör kontrollera eller göra härnäst",plain:"🌍 Enkel förklaring / översättning"});
Object.assign(M["m9707_TOOLS"]["SV"],{pdf:{title:"PDF-analys",desc:"Lägg till ett PDF-dokument på upp till 10 sidor. Sense Bridge extraherar text och skickar skannade sidor till OCR.",card:"Läs och förklara ett flersidigt PDF-dokument.",run:"Analysera PDF",placeholder:"Du kan också klistra in text från ett PDF-dokument...",note:"Testversion: högst 10 sidor. Dokument lagras inte.",labels:["📋 Vad dokumentet är","🏛️ Utfärdare och syfte","📅 Tidsfrister och datum","⚠️ Viktiga eller oklara punkter","➡️ Vad du ska göra härnäst","🌍 Enkel förklaring"]},form:{title:"Formulärhjälp",desc:"Klistra in ett formulär eller lägg till upp till 5 foton av sidor i följd.",card:"Förklaring av fält, nödvändig information och dokument.",run:"Förklara formulär",placeholder:"Klistra in formulärtexten eller beskriv vad du behöver hjälp med...",note:"Sense Bridge förklarar fälten men fyller inte i dina uppgifter och skickar inte formuläret.",labels:["📋 Formulärets syfte","📝 Hur fälten fylls i","📎 Nödvändig information och dokument","⚠️ Fält som kräver uppmärksamhet","➡️ Nästa steg","🌍 Enkel förklaring"]},photo:{title:"Fotoanalys",desc:"Lägg till upp till 5 foton med text, ett meddelande, en skylt eller ett dokument.",card:"Läs och förklara text som syns på foton.",run:"Analysera foton",placeholder:"Beskriv gärna fotot eller vad du vill veta...",note:"Fotot bör vara skarpt, väl belyst och innehålla all text.",labels:["🖼️ Vad fotona visar","📄 Extraherat innehåll","🏛️ Avsändare eller källa","⚠️ Viktiga signaler","➡️ Vad du ska göra härnäst","🌍 Enkel förklaring / översättning"]},bill:{title:"Räkningar och fakturor",desc:"Klistra in fakturatext eller lägg till upp till 5 foton av sidorna.",card:"Belopp, betalningsfrister, poster och möjliga oklara avgifter.",run:"Förklara faktura",placeholder:"Klistra in räkningen eller fakturatexten...",note:"Sense Bridge ger informativ vägledning. Kontrollera mottagare och bankuppgifter innan du betalar.",labels:["🧾 Vad fakturan gäller","💶 Belopp och poster","📅 Betalningsfrist och metod","⚠️ Avgifter eller oklara punkter","➡️ Vad du ska kontrollera före betalning","🌍 Enkel förklaring"]}});

Object.assign(M["m5723_copy"]["SV"],{screenshot:{what:"Det här ser ut som en skärm eller varning som bör kontrolleras.",next:"Tryck inte på knappar eller länkar innan du har verifierat källan. Jämför med den officiella webbplatsen.",reply:"Om det påstås komma från en institution, öppna den officiella webbplatsen själv."},link:{what:"Det här är en länk eller webbadress som bör kontrolleras.",next:"Kontrollera domänen själv. Logga inte in via en länk i ett meddelande. Öppna den officiella webbplatsen själv.",reply:"Det är säkrare att öppna den officiella webbplatsen via sökning eller ett sparat bokmärke."},message:{what:"Det här ser ut som ett meddelande som bör kontrolleras för nätfiske eller press.",next:"Kontrollera avsändaren, domänen och om meddelandet pressar dig att agera snabbt. Dela inte inloggningsuppgifter.",reply:"Tack för meddelandet. Jag kommer att verifiera detta via den officiella kontaktkanalen."},reply:{what:"Det här är en situation där ett lugnt svar kan förberedas.",next:"Svara kort och tydligt utan onödiga personuppgifter.",reply:"Tack för meddelandet. Förklara gärna ärendet och vilken åtgärd som krävs av mig."},conversation:{what:"Det här är ett ämne för ett samtal som är bra att förbereda.",next:"Skriv ner målet, dokumenten du behöver ta med och 2–3 frågor.",reply:"Jag vill reda ut detta lugnt. Berätta gärna vilka nästa steg är och vilka dokument som behövs."}});

})(window);

// Nordic install dialog
window.SB_INSTALL_I18N = window.SB_INSTALL_I18N || {};
window.SB_INSTALL_I18N.SV = {
  title: "Lägg till Sense Bridge<br>på din telefon",
  text: "Ha alltid Sense Bridge nära till hands.",
  privacy: "Dina brev och bilder sparas eller delas inte.",
  step: "Tryck på webbläsarens meny med <b>tre punkter</b> och välj:",
  add: "Lägg till på startskärmen",
  ok: "Jag förstår"
};

/* Nordic full-message audit patch v4 — function-valued UI strings only. */
(function(w){"use strict";const M=w.SB_I18N&&w.SB_I18N.modules;if(!M)return;
if(M["m9439_COPY"]&&M["m9439_COPY"].SV){M["m9439_COPY"].SV.count=n=>`Valda: ${n}/5`;M["m9439_COPY"].SV.reading=(i,n)=>`Läser sida ${i} av ${n}...`;}
if(M["m9695_COMMON"]&&M["m9695_COMMON"].SV){M["m9695_COMMON"].SV.selected=n=>`Valda: ${n}/5`;M["m9695_COMMON"].SV.reading=(i,n)=>`Läser sida ${i} av ${n}...`;}
})(window);
